import Link from "next/link";
import Script from "next/script";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AdSense from "@/components/AdSense";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-gray-900 min-h-screen flex flex-col`}>
        {/* ヘッダー */}
        <header className="w-full border-b bg-white dark:bg-gray-800 shadow-sm sticky top-0 z-50">
          <nav className="w-full mx-auto flex justify-between items-center px-4 py-3 md:px-6">
            <Link href="/" className="font-bold text-lg md:text-xl text-blue-700 dark:text-blue-400">
              ユナコミュ
            </Link>
            <div className="flex gap-4 md:gap-6 text-gray-700 dark:text-gray-300 text-sm md:text-base">
              <Link href="/pokemon" className="hover:text-blue-600 dark:hover:text-blue-400 transition">ポケモン一覧</Link>
            </div>
          </nav>
        </header>
        {/* メインコンテンツ */}
        <main className="flex-1 w-full px-4 py-6 md:px-6 md:py-8">{children}</main>
        {/* 広告枠（ページ下部） */}
        <aside className="w-full bg-white dark:bg-gray-800 border-t border-b py-6">
          <div className="px-4 md:px-6">
            <AdSense />
          </div>
        </aside>
        {/* フッター */}
        <footer className="w-full border-t bg-white dark:bg-gray-800 py-4 mt-8">
          <div className="flex flex-col md:flex-row justify-between items-center text-gray-500 dark:text-gray-400 text-xs md:text-sm gap-3 px-4 md:px-6">
            <div>© 2025 ユナコミュ</div>
            <div className="flex gap-4">
              <Link href="/terms" className="hover:underline transition">利用規約</Link>
              <Link href="/privacy" className="hover:underline transition">プライバシーポリシー</Link>
            </div>
          </div>
        </footer>
        {/* Google AdSense スクリプト */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3903983116971021"
          crossOrigin="anonymous"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
